<a href="https://colab.research.google.com/github/MaheshUike/AI-practice-1/blob/main/sklearn_Encoding_techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [16]:
df =  pd.read_csv("/content/CAR DETAILS FROM CAR DEKHO.csv")

In [17]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [18]:
# let's train the  entire data first then will implement the  encoding  directly

In [19]:
# name is not important here so let's drop that first
df.drop("name", axis = 1, inplace = True)

In [20]:
df.head()

,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [21]:
# we are going to train the model on fuel seller type, transmission and owner , fuels would be our output model
new_df = df[["fuel","seller_type","transmission","owner"]]

In [22]:
new_df.head()

     fuel seller_type transmission         owner
0  Petrol  Individual       Manual   First Owner
1  Petrol  Individual       Manual   First Owner
2  Diesel  Individual       Manual   First Owner
3  Petrol  Individual       Manual   First Owner
4  Diesel  Individual       Manual  Second Owner

In [23]:
# let's train the model using train test split
X = new_df.drop("fuel",axis = 1)
y = new_df["fuel"]

In [24]:
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size = 0.2, random_state = 42)

In [25]:
X_train.head()

     seller_type transmission         owner
227   Individual       Manual   First Owner
964   Individual       Manual   First Owner
2045  Individual       Manual  Second Owner
1025  Individual       Manual   First Owner
4242      Dealer       Manual   First Owner

# After fit_transform(data) always use transform(data)
* fit_transoform(data) -->  it learns from the data
* transform() uses what was learned by fit() to convert the data

# **Encoding Techniques**
!important all techniques must be used after train test split


* **Label Encoding**
* It should be only use to the output  column only not complusory but its  
good practice



> le = LabelEncoder()


> variable_name = le.fit_transform("data")





---




* **Ordinal Encoding**


* It should be used to the training data its good practice

In [26]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

In [29]:
le = LabelEncoder()

In [30]:
# Labelling output columns which is fuel in our case
y_train_label = le.fit_transform(y_train)
y_test_label = le.transform(y_test)

In [31]:
y_train_label

array([1, 1, 4, ..., 1, 1, 4])

In [38]:
# convert above array into the  dataframe
y_train_label = pd.DataFrame(y_train_label, columns = ["fuel"])
y_test_label = pd.DataFrame(y_test_label, columns =["fuel"])

In [42]:
y_train_label.head()

   fuel
0     1
1     1
2     4
3     1
4     1

Now Ordinal Encoding --> ordered encoding  first owner, second owner , third owner --> it is order

In [43]:
oe = OrdinalEncoder()

In [45]:
X_train_label = oe.fit_transform(X_train)
X_test_label = oe.transform(X_test)

In [47]:
X_train_label

array([[1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 2.],
       ...,
       [0., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.]])

In [48]:
# converting it into the data frame
X_train_label = pd.DataFrame(X_train_label, columns= X_train.columns)
X_test_label = pd.DataFrame(X_test_label, columns=X_train.columns)

In [49]:
X_train_label

      seller_type  transmission  owner
0             1.0           1.0    0.0
1             1.0           1.0    0.0
2             1.0           1.0    2.0
3             1.0           1.0    0.0
4             0.0           1.0    0.0
...           ...           ...    ...
3467          1.0           1.0    0.0
3468          1.0           1.0    0.0
3469          0.0           1.0    0.0
3470          1.0           1.0    0.0
3471          1.0           1.0    0.0

[3472 rows x 3 columns]